
package windows;

import javax.swing.JOptionPane;

public class inicio extends javax.swing.JFrame {
    
    public inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Interfaz signo zodiacal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resultado = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buscar = new javax.swing.JButton();
        mensaje_introducir_datos = new javax.swing.JLabel();
        entrada_dias = new javax.swing.JTextField();
        entrada_mes = new javax.swing.JTextField();
        mesNacimiento = new javax.swing.JLabel();
        diaNacimiento = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(490, 420));
        setPreferredSize(new java.awt.Dimension(495, 405));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultado.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        resultado.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        resultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resultadoKeyReleased(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        resultado.setViewportView(jTextArea1);

        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 248, 300, 110));

        buscar.setBackground(new java.awt.Color(153, 153, 153));
        buscar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buscar.setText("Buscar");
        buscar.setEnabled(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, 40));

        mensaje_introducir_datos.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        mensaje_introducir_datos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mensaje_introducir_datos.setText("Introduzca los siguientes datos:");
        jPanel1.add(mensaje_introducir_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 120, 320, -1));

        entrada_dias.setBackground(new java.awt.Color(102, 102, 102));
        entrada_dias.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        entrada_dias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entrada_dias.setMaximumSize(new java.awt.Dimension(60, 60));
        entrada_dias.setMinimumSize(new java.awt.Dimension(1, 31));
        entrada_dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada_diasActionPerformed(evt);
            }
        });
        entrada_dias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                entrada_diasKeyReleased(evt);
            }
        });
        jPanel1.add(entrada_dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 159, 60, 30));

        entrada_mes.setBackground(new java.awt.Color(102, 102, 102));
        entrada_mes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        entrada_mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entrada_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada_mesActionPerformed(evt);
            }
        });
        entrada_mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                entrada_mesKeyReleased(evt);
            }
        });
        jPanel1.add(entrada_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 200, 60, 30));

        mesNacimiento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mesNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mesNacimiento.setText("Mes de nacimiento: ");
        jPanel1.add(mesNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 192, 180, 40));

        diaNacimiento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        diaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        diaNacimiento.setText("Dia de nacimiento: ");
        jPanel1.add(diaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 170, 40));

        titulo.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Calcula tu signo Zodiacal");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 480, 50));

        btn_salir.setBackground(new java.awt.Color(51, 51, 51));
        btn_salir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(204, 0, 51));
        btn_salir.setText("X");
        btn_salir.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 30));

        fondo.setBackground(new java.awt.Color(27, 73, 163));
        fondo.setForeground(new java.awt.Color(34, 54, 113));
        fondo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fondoKeyReleased(evt);
            }
        });
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void entrada_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrada_mesActionPerformed

    private void entrada_diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada_diasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrada_diasActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        int dia = 0;
        int mes = 0;
        
        try {
            dia = Integer.parseInt(entrada_dias.getText());
            mes = Integer.parseInt(entrada_mes.getText());
            
            if (mes == 1 && dia >= 21 && dia <= 31 || mes == 2 && dia >= 1 && dia <= 19) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Acuario *\n\n- Elemento: Aire.\n- Puntos fuertes: innovador y vanguardista.");
            }
            else if (mes == 2 && dia >= 20 && dia <= 29 || mes == 3 && dia >= 1 && dia <= 20) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Piscis *\n\n- Elemento: Agua.\n- Puntos fuertes: tacto y tenacidad.");
            }
            else if (mes == 3 && dia >= 21 && dia <= 31 || mes == 4 && dia >= 1 && dia <= 20) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Aries *\n\n- Elemento: Fuego.\n- Puntos fuertes: rapidez y fuerza.");
            }
            else if (mes == 4 && dia >= 21 && dia <= 30 || mes == 5 && dia >= 1 && dia <= 21) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Tauro *\n\n- Elemento: Tierra.\n- Puntos fuertes: Resistencia y prudencia.");
            }
            else if (mes == 5 && dia >= 22 && dia <= 31 || mes == 6 && dia >= 1 && dia <= 21) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Géminis *\n\n- Elemento: Aire.\n- Puntos fuertes: agilidad y adaptacion.");
            }
            else if (mes == 6 && dia >= 22 && dia <= 30 || mes == 7 && dia >= 1 && dia <= 22) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Cáncer *\n\n- Elemento: Agua.\n- Puntos fuertes: perseverancia y creatividad.");
            }
            else if (mes == 7 && dia >= 23 && dia <= 31 || mes == 8 && dia >= 1 && dia <= 23) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Leo *\n\n- Elemento: Fuego.\n- Puntos fuertes: bondad y organizado.");
            }
            else if (mes == 8 && dia >= 24 && dia <= 31 || mes == 9 && dia >= 1 && dia <= 23) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Virgo *\n\n- Elemento: Tierra.\n- Puntos fuertes: precision y logica.");
            }
            else if (mes == 9 && dia >= 24 && dia <= 30 || mes == 10 && dia >= 1 && dia <= 23) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Libra *\n\n- Elemento: Aire.\n- Puntos fuertes: equilibrio y justicia.");
            }
            else if (mes == 10 && dia >= 24 && dia <= 31 || mes == 11 && dia >= 1 && dia <= 22) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Escorpio *\n\n- Elemento: Agua.\n- Puntos fuertes: tenacidad y tacto.");
            }
            else if (mes == 11 && dia >= 23 && dia <= 30 || mes == 12 && dia >= 1 && dia <= 21) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Sagitario *\n\n- Elemento: Fuego.\n- Punto fuerte: optimismo.");
            }
            else if (mes == 12 && dia >= 22 && dia <= 31 || mes == 1 && dia >= 1 && dia <= 20) {
                jTextArea1.setText("Tu signo zodiacal es:\n* Capricornio *\n\n- Elemento: Tierra.\n- Punto fuerte: resistencia.");
            }
            else {
                JOptionPane.showMessageDialog(null,"Has puesto un mes o un dia que no existen");
            }
             
        }
        catch (NumberFormatException nfe) {
           JOptionPane.showMessageDialog(null,"No ingreso un numero valida.\nVuelva a ingresar su dia o mes de\nnacimiento utilizando unicamente numeros."); 
        }
        
    }//GEN-LAST:event_buscarActionPerformed

    private void fondoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fondoKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fondoKeyReleased

    private void entrada_mesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entrada_mesKeyReleased
        // TODO add your handling code here:
        habilitar_btn();
    }//GEN-LAST:event_entrada_mesKeyReleased

    private void entrada_diasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entrada_diasKeyReleased
        // TODO add your handling code here:
        habilitar_btn();
    }//GEN-LAST:event_entrada_diasKeyReleased

    private void resultadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoKeyReleased

    public void habilitar_btn () {
        if (!entrada_dias.getText().isEmpty() && !entrada_mes.getText().isEmpty()) {
            buscar.setEnabled(true);
        }
        else {
            buscar.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel diaNacimiento;
    private javax.swing.JTextField entrada_dias;
    private javax.swing.JTextField entrada_mes;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel mensaje_introducir_datos;
    private javax.swing.JLabel mesNacimiento;
    private javax.swing.JScrollPane resultado;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
